name: Build RHEL bootc image with GHA
on:
  push:
    branches:
      - '*'           # All branches
      - '**'          # All branches including those with slashes (feature/branch-name)
  pull_request:       # Also run on pull requests for testing
    branches:
      - '*'
  workflow_dispatch:   # Allow manual triggering

jobs:
  rhel-bootc-image-build:
    name: Build RHEL bootc image with repo access
    runs-on: ubuntu-latest
    env:
      # Disable Subscription Manager container passthrough
      SMDEV_CONTAINER_OFF: 1
      # Subscription Manager credentials - uses repository secrets
      # RHT_ORGID: "${{ secrets.RHT_ORGID }}"
      # RHT_ACT_KEY: "${{ secrets.RHT_ACT_KEY }}"
      
      # Source registry for base image
      SOURCE_REGISTRY_HOST: "registry.redhat.io"
      # Source credentials - uses repository secrets
      # SOURCE_REGISTRY_USER: "${{ secrets.SOURCE_REGISTRY_USER }}"
      # SOURCE_REGISTRY_PASSWORD: "${{ secrets.SOURCE_REGISTRY_PASSWORD }}"

      # Containerfile to build
      CONTAINERFILE: Containerfile

      # Destination image namespace and name (eg: myrepo/myimage)
      DEST_IMAGE: "${{ github.actor }}/${{github.event.repository.name}}"

      # List of tags to publish
      TAGLIST: latest ${{ github.sha }} ${{ github.ref_name }}

      # Destination registry for built images
      DEST_REGISTRY_HOST: "ghcr.io"
      # Destination credentials - uses platform variables and secrets
      # DEST_REGISTRY_USER: "${{ github.actor }}"
      # DEST_REGISTRY_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"

    container:
      image: registry.access.redhat.com/ubi9/ubi
      options: --privileged
    permissions:
      contents: write
      packages: write

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Access a subscription via activation key
        run: subscription-manager register --org=${{ secrets.RHT_ORGID }} --activationkey=${{ secrets.RHT_ACT_KEY }} 

      - name: Get container tools in UBI builder
        run: dnf -y install podman buildah skopeo wget ansible-core 

      - name: Install Red Hat COP AAP utilities collection
        run: |
          ansible-galaxy collection install git+https://github.com/redhat-cop/aap_utilities.git

      - name: Download AAP setup bundle using Red Hat COP utilities
        run: ansible-playbook download-aap-setup.yml -e "aap_setup_download_url=${{ secrets.TARBALL }}" -e "aap_setup_dest_directory=/__w/redhat-image-mode-aap/redhat-image-mode-aap" -e "aap_setup_bundle_name=ansible-automation-platform-containerized-setup-2.5-15.tar.gz"

      # workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      - name: Workaround open podman-login action issue
        env:
          auth: "{ \"auths\": {} }"
        run: |
          mkdir -p $HOME/.docker
          echo $auth > $HOME/.docker/config.json

      - name: Log in to the RHT terms based registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.SOURCE_REGISTRY_HOST }}
          username: ${{ secrets.SOURCE_REGISTRY_USER }}
          password: ${{ secrets.SOURCE_REGISTRY_PASSWORD }}
          auth_file_path: /run/containers/0/auth.json

      - name: Use buildah bud to create the image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.DEST_IMAGE }}
          tags: ${{ env.TAGLIST }}
          containerfiles: ${{ env.CONTAINERFILE }}
          build-args: |
            ANSIBLE_USER_PASS=${{ secrets.ANSIBLE_USER_PASS }}

      - name: Log in to the GitHub Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.DEST_REGISTRY_HOST }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /run/containers/0/auth.json

      - name: Push to GitHub Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.DEST_REGISTRY_HOST }}

      - name: Clean up the subscription
        if: always()
        run: subscription-manager unregister
